"""Build the tiny Android reflection bridge and embed its DEX in the payload."""
import hashlib
import pathlib
import shutil
import subprocess
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
R8 = ROOT / 'tools/downloads/r8-8.3.37.jar'
SHA = '59753e70a74f918389cc87f1b7d66b5c0862932559167425708ded159e3de439'
if not R8.exists():
    R8.parent.mkdir(parents=True, exist_ok=True)
    urllib.request.urlretrieve('https://storage.googleapis.com/r8-releases/raw/8.3.37/r8lib.jar', R8)
if hashlib.sha256(R8.read_bytes()).hexdigest() != SHA:
    raise SystemExit('R8 checksum mismatch')
build = ROOT / 'build/bridge'
classes, dex = build / 'classes', build / 'dex'
for folder in (classes, dex):
    folder.mkdir(parents=True, exist_ok=True)
subprocess.run([shutil.which('javac'), '--release', '8', '-d', str(classes),
                str(ROOT / 'bridge/src/rt/internal/Bridge.java')], check=True)
subprocess.run([shutil.which('java'), '-cp', str(R8), 'com.android.tools.r8.D8',
                '--min-api', '26', '--no-desugaring', '--output', str(dex),
                str(classes / 'rt/internal/Bridge.class')], check=True)
data = (dex / 'classes.dex').read_bytes()
header = '/* Generated by tools/build_bridge.py. */\nstatic const unsigned char cf_bridge_dex[] = {\n'
header += '\n'.join(','.join(str(b) for b in data[i:i+24])+',' for i in range(0, len(data), 24))
header += '\n};\n'
(build / 'bridge_dex.h').write_text(header, encoding='ascii')
print(f'Input bridge DEX: {len(data)} bytes')
